### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by skymilong** [yongjun925/autocollectenergy#5]
现在一打开蚂蚁森林就闪退呀

**Comment by JoffreyN** [comment]
我的没有哎

**Comment by skymilong** [comment]
> 我的没有哎

你的可以正常收集吗

**Comment by JoffreyN** [comment]
> 
> 
> > 我的没有哎
> 
> 你的可以正常收集吗

可以啊

**Comment by skymilong** [comment]
> > > 我的没有哎
> > 
> > 
> > 你的可以正常收集吗
> 
> 可以啊

估计是版本问题，我的38的不行。35可以
